language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dc1177/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dc1177/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-000649523684"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY